### ISSUE TITLE
Notes on new 2 GB Raspberry Pi 5 D0 stepping

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pi-overvolt#4]
The new Pi 5 has a D0 stepping, which supposedly has a smaller die (for better cost per chip) with some of the 'dark silicon' Broadcom used for other purposes removed.

Right now it seems to only be available on the Pi 5 2GB, so I ordered a few samples and am testing them...

I have found a few things already:

  - Geekbench 6 won't complete (even at default clocks) as the OOM kills it when it runs the Photo Filter multicore test.
  - I can get one of my samples to run somewhat stably up to 3.5 GHz unmodified (with this firmware hack), but 3.6 GHz results in a number of kernel memory errors, and ultimately a kernel panic. (This is with a heatsink underneath and peltier on top).

**Comment by geerlingguy** [comment]
![DSC00448](https://github.com/user-attachments/assets/53b7b016-090f-4434-82bc-63981c77f57c)

CPU die dimensions are 6.30mm x 5.98mm (37.674mm<sup>2</sup>)

Old C0 stepping that I have on hand measured 6.47 x 8.63mm  (55.836mm<sup>2</sup>)

**Comment by geerlingguy** [comment]
CNX Software posted: [Comparison of Raspberry Pi 5 with 2GB and 8GB RAM – Hardware, benchmarks, and power consumption](https://www.cnx-software.com/2024/08/27/comparison-of-raspberry-pi-5-with-2gb-and-8gb-ram-hardware-benchmarks-and-power-consumption/).

| | Raspberry Pi 5 2GB | Raspberry Pi 5 8GB |
| --- | --- | --- |
| Power off | 1.8 Watts | 2.7 Watts |
| Idle (ondemand) | 2.7 Watts | 3.5 Watts |
| Idle (performance) | 4.4 Watts | 5.5 Watts |

A couple notes:

  - I did observe idle 2.4W on the Pi 5 2GB I was testing. Didn't do much comparison on thermals yet. 3.2W on the Pi 5 4GB, need to re-test though with controlled conditions.
  - It would make sense for a 2GB Pi 5 to use less power while turned on, as it 
  - The power off power can be much lower if you use `POWER_OFF_ON_HALT=1` like I mention in the blog post [Reducing Raspberry Pi 5's power consumption by 140x](https://www.jeffgeerling.com/blog/2023/reducing-raspberry-pi-5s-power-consumption-140x)

**Comment by geerlingguy** [comment]
Some of my own testing:

| | Pi 5 2GB D0 | Pi 5 4GB C1 | Delta |
| --- | --- | --- | --- |
| Idle power | TODO | 3.4W | TODO |
| Idle temp | TODO | TODO | TODO |
| stress-ng power | TODO | 9.8W | TODO |
| stress-ng temp | TODO | TODO | TODO |

**Comment by ThomasKaiser** [comment]
> 0.2W (+10%)

Should read "0.9W (+10%)" both times :)

**Comment by geerlingguy** [comment]
@ThomasKaiser - Ah, drat, formatting markdown tables is always fun :) Fixed it!

**Comment by ThomasKaiser** [comment]
> probably because of swap

`sbc-bench -G` would have shown the full story since monitoring for swapping and the other stuff ruining benchmark scores. 

Or firing up `sbc-bench -R` and then once it's ready to monitor other benchmark executions running Geekbench in another Terminal. When finished benchmarking and stopping sbc-bench via [ctrl]-[c] it will tell whether swapping, throttling, frequency capping (and so forth) happened while the other benchmark has been executed :)

**Comment by geerlingguy** [comment]
I think my preliminary exploration is done, will be posting this on my blog/YouTube soon (hopefully Thurs/Fri, as long as baby doesn't arrive before I can post it lol).
